name: Install Devine, Video Processing Tools, and Serve with Cloudflare Tunnel

on:
  workflow_dispatch:
    inputs:
      source:
        description: 'Specify the source (e.g., ROKU, TUBI)'
        required: true
        default: 'ROKU'
      url:
        description: 'Specify the URL for the video stream to download'
        required: true
        default: 'https://therokuchannel.roku.com/details/80ce7c581645518da7b1e780c3b8ed6d/fargo?source=bing'

jobs:
  install-devine-and-tools:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Install system dependencies (CCExtractor, FFmpeg, MKVToolNix, aria2c)
    - name: Install required system tools with APT
      run: |
        sudo apt-get update
        sudo apt-get install -y ccextractor ffmpeg mkvtoolnix aria2

    # Download and install shaka-packager from GitHub
    - name: Download and install shaka-packager
      run: |
        wget https://github.com/shaka-project/shaka-packager/releases/download/v3.2.0/packager-linux-x64 -O shaka-packager
        chmod +x shaka-packager
        sudo mv shaka-packager /usr/bin/packager

    - name: Install Cloudflared
      run: |
        wget https://github.com/cloudflare/cloudflared/releases/download/2024.9.1/cloudflared-linux-amd64 -O cloudflared
        chmod +x cloudflared
        sudo mv cloudflared /usr/bin/cloudflared

    # Download the zipped Devine version from the provided URL
    - name: Download custom Devine package
      run: |
        wget https://pixeldrain.com/api/file/KPkBJhAD -O devine.zip
        unzip devine.zip

     # Create directories for Devine WVDs
    - name: Create directories for Devine WVDs
      run: |
        mkdir -p $HOME/.local/share/devine/WVDs

    # Download device.wvd into the Devine WVDs folder
    - name: Download device.wvd
      run: |
        wget https://pixeldrain.com/api/file/46xtUP2e -O $HOME/.local/share/devine/WVDs/device.wvd


    # Install Python dependencies for Devine
    - name: Install Python dependencies
      run: |
        pip install devine

    # Run Devine Python command with dynamic source and URL
    - name: Run Devine to download video stream
      run: |
        python3 -m devine dl ${{ inputs.source }} ${{ inputs.url }}

    # Start a simple HTTP server in the user folder
    - name: Start HTTP Server
      run: |
        cd $HOME/Downloads/devine
        python3 -m http.server 8000 &

    # Run Cloudflare Tunnel to expose the HTTP server
    - name: Expose with Cloudflare Tunnel
      run: |
        cloudflared tunnel --url http://localhost:8000

    # Verify installation of tools
    - name: Verify installations
      run: |
        ccextractor --version
        ffmpeg -version
        mkvmerge --version
        packager --version
        aria2c --version
