name: Oookla Speedtest

on: 
  push: 
    branches:
      - main  # Change this to your target branch if needed

jobs:
  speedtest:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Install speedtest-cli
    - name: Install speedtest-cli
      run: |
        curl -s https://packagecloud.io/install/repositories/ookla/speedtest-cli/script.deb.sh | sudo bash
        sudo apt-get install -y speedtest-cli  # Added -y to automatically confirm installation

    # Test the speed
    - name: Test the speed
      run: speedtest-cli  # Use the correct command
